<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" href="all.css">';
echo '<title>À propos</title>';
echo '</head>';
echo '';
echo '';
echo '<body>';
echo '<div class="nav"><center>';
echo '<ul nav-link>';
echo '<li><a href="accueil.php">Accueil</a></li>';
echo '<li class="active"><a href="a-propos.php">À propos</a></li>';
echo '<li><a href="competences.php">Compétences</a></li>';
echo '<li><a href="experience.php">Expérience</a></li>';
echo '<li><a href="formation.php">Formation</a></li>';
echo '<li><a href="contact.php">Contact</a></li>';
echo '</ul>';
echo '</div></center>';
echo '';
echo '<div class="container"><center>';
echo '<div class="paper">';
echo '<h1>À propos</h1>';
echo '<p>Mon nom est Tom Dufour je suis un étudiant à Caensup Sainte-Ursule. Je suis née en France j ai 18 ans je suis passionné par l informatique, j aime beaucoup le réseau Montage pc répartion hardware.';
echo '<h1></h1>';
echo '<h1></h1>';
echo '<img src="https://media.istockphoto.com/id/1058262630/fr/vectoriel/site-internet-r%C3%A9actif-de-cr%C3%A9ation-pour-de-multiples-plates-formes-interface-mobile.jpg?s=612x612&w=0&k=20&c=zYrOuvoxu95JqwLMotASsrmYRWxZ71p0lBH1MkMNrqg=">';
echo '</div>';
echo '</div></center>';
echo '</ul>';
echo '</div>';
echo '</body>';
echo '</html>';
?>