<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" href="all.css">';
echo '<title>Mes Compétences</title>';
echo '</head>';
echo '';
echo '';
echo '<body>';
echo '<div class="nav"><center>';
echo '<ul nav-link>';
echo '<li><a href="accueil.php">Accueil</a></li>';
echo '<li><a href="a-propos.php">À propos</a></li>';
echo '<li class="active"><a href="competences.php">Compétences</a></li>';
echo '<li><a href="experience.php">Expérience</a></li>';
echo '<li><a href="formation.php">Formation</a></li>';
echo '<li><a href="contact.php">Contact</a></li>';
echo '</ul>';
echo '</div></center>';
echo '<div class="paper">';
echo '<h1>Compétences</h1>';
echo '<div class="nav-competences">';
echo '<h3>|Réseaux|</h3>';
echo '<div class="nav-competences-p">';
echo '<p><a>Conf. d un Switch</a></p>★★★★✩';
echo '<p><a>Conf. d un Router</a></p>★★★★✩';
echo '<p><a>Conf. d un Firewall</a></p>★★✩✩✩';
echo '<p><a>Conf. d un Serveur</a></p>★★★✩✩';
echo '<p><a>Installation de Fibre</a></p>★★✩✩✩';
echo '</div>';
echo '<h3>|Codage|</h3>';
echo '<div class="nav-competences-p">';
echo '<p><a>HTML</a></p>★★✩✩✩';
echo '<p><a>CSS</a></p>★★✩✩✩';
echo '<p><a>PHP</a></p>★★✩✩✩';
echo '<p><a>YAMLE</a></p>★★✩✩✩';
echo '<p><a>JAVA SCRIPT</a></p>★★✩✩✩';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</body>';
echo '</html>';