<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" href="all.css">';
echo '<title>Contact</title>';
echo '</head>';
echo '';
echo '';
echo '<body>';
echo '<div class="nav"><center>';
echo '<ul nav-link>';
echo '<li><a href="accueil.php">Accueil</a></li>';
echo '<li><a href="a-propos.php">À propos</a></li>';
echo '<li><a href="competences.php">Compétences</a></li>';
echo '<li><a href="experience.php">Expérience</a></li>';
echo '<li><a href="formation.php">Formation</a></li>';
echo '<li class="active"><a href="contact.php">Contact</a></li>';
echo '</ul>';
echo '</div></center>';
echo '';
echo '<div class="container"><center>';
echo '<div class="paper">';
echo '<h1>Contact</h1>';
echo '<p>?</p>';
echo '</div></center>';
echo '</div>';
echo '</body>';
echo '</html>';
?>