<?php
echo '<!DOCTYPE html>';
echo '<html>';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<link rel="stylesheet" href="all.css">';
echo '<title>Experience</title>';
echo '</head>';
echo '';
echo '';
echo '<body>';
echo '<div class="nav"><center>';
echo '<ul nav-link>';
echo '<li><a href="accueil.php">Accueil</a></li>';
echo '<li><a href="a-propos.php">À propos</a></li>';
echo '<li><a href="competences.php">Compétences</a></li>';
echo '<li class="active"><a href="experience.php">Expérience</a></li>';
echo '<li><a href="formation.php">Formation</a></li>';
echo '<li><a href="contact.php">Contact</a></li>';
echo '</ul>';
echo '</div></center>';
echo '';
echo '<div class="container"><center>';
echo '<div class="paper">';
echo '<h1>Expérience</h1>';
echo '<div class="nav-competences-p">';
echo '<p>Décembre 2018 : Stage de 1 semaine dans les domaines de l’informatique et de la téléphonie à VIVRE MOBILE.</p>';
echo '<p>ㅤ</p>';
echo '<p>Décembre 2019 : Stage de 3 semaines dans les domaines de l’informatique et de l’audiovisuel à Lisi Medical à HEROUVILLE ST CLAIR.</p>';
echo '<p>ㅤ</p>';
echo '<p>Juillet 2020 : emploi saisonnier aux espaces verts pour la ville d EVRECY.</p>';
echo '<p>ㅤ</p>';
echo '<p>25 janvier au 25 février, stage dans le réseau et l’informatique chez Lisi Médical à HEROUVILLE ST CLAIR</p>';
echo '<p>ㅤ</p>';
echo '<p>Juillet, Août 2021 : emploi saisonnier à Macdonald à Bretteville Sur Odon</p>';
echo '<p>ㅤ</p>';
echo '<p>22 novembre au 17 décembre 2021, stage dans le réseau et l’informatique chez Partélios Habitat à SAINT-CONTEST.</p>';
echo '<p>ㅤ</p>';
echo '<p>14 Mars au 8 Avril 2022, stage dans le réseau et l’informatique au Rectorat de Caen.</p>';
echo '<p>ㅤ</p>';
echo '</div></center>';
echo '</div>';
echo '</body>';
echo '</html>';
?>